import { describe, expect, it } from 'vitest';
import { UUID_SHAPE } from './uuid';

/**
 * Pins the difference between this shape check and `z.string().uuid()`, because
 * the stricter check has now rejected a valid identifier twice in this codebase —
 * once for a wallet-link nonce and once for a notification id — and both times it
 * surfaced as a confusing 400 rather than as an obvious type error.
 */
describe('UUID_SHAPE', () => {
  it('accepts a v4 uuid', () => {
    expect(UUID_SHAPE.test('9f8b7c6d-1a2b-4c3d-8e4f-5a6b7c8d9e0f')).toBe(true);
  });

  it('accepts a uuid whose version nibble is not 1-5', () => {
    // A `uuidv7()` value, and the shape generated by the fixtures in
    // `tests/notification-model.test.ts`. RFC 4122 version rules reject these;
    // Postgres does not.
    expect(UUID_SHAPE.test('0190f2a1-2b3c-7d4e-9f50-1a2b3c4d5e6f')).toBe(true);
    expect(UUID_SHAPE.test('99999999-9999-9999-9999-999999999999')).toBe(true);
  });

  it('accepts a uuid whose variant nibble is not 8-9 or a-b', () => {
    // 'c' as the variant nibble is outside RFC 4122's set but is a perfectly
    // valid 128-bit value to Postgres.
    expect(UUID_SHAPE.test('11111111-1111-1111-c111-111111111111')).toBe(true);
  });

  it('accepts uppercase hex', () => {
    expect(UUID_SHAPE.test('9F8B7C6D-1A2B-4C3D-8E4F-5A6B7C8D9E0F')).toBe(true);
  });

  it('rejects a value of the wrong length', () => {
    expect(UUID_SHAPE.test('9f8b7c6d-1a2b-4c3d-8e4f-5a6b7c8d9e0')).toBe(false);
    expect(UUID_SHAPE.test('9f8b7c6d-1a2b-4c3d-8e4f-5a6b7c8d9e0ff')).toBe(false);
  });

  it('rejects a malformed value', () => {
    expect(UUID_SHAPE.test('not-a-uuid')).toBe(false);
    expect(UUID_SHAPE.test('')).toBe(false);
    // A contract address, which is the other identifier shape in this API and
    // must not be mistaken for a user or notification id.
    expect(UUID_SHAPE.test(`C${'A'.repeat(55)}`)).toBe(false);
  });

  it('rejects a value with the groups in the wrong places', () => {
    expect(UUID_SHAPE.test('9f8b7c6d1-a2b-4c3d-8e4f-5a6b7c8d9e0f')).toBe(false);
    expect(UUID_SHAPE.test('9f8b7c6d-1a2b-4c3d-8e4f5a6b7c8d9e0f')).toBe(false);
  });
});
