-- Susu Protocol — profiles
--
-- The table and its security posture ship together on purpose. A table without
-- RLS is a table the browser can read, so there is no useful sense in which
-- "create the table now, secure it later" is a smaller change; it is the same
-- change with a window in between.
--
-- Generated by `drizzle-kit generate`, then extended by hand. Drizzle cannot
-- express RLS, policies, column-level grants, or a conditional foreign key, and
-- all four are requirements here rather than embellishments. Regenerating this
-- file would drop them, so it is reviewed as source rather than produced as
-- output.

CREATE TABLE "profiles" (
	"user_id" uuid PRIMARY KEY NOT NULL,
	"display_name" text,
	"avatar_path" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- Supabase-managed roles, created only when absent.
--
-- `anon`, `authenticated` and `service_role` exist in a hosted project. Plain
-- PostgreSQL — which the CI guards run against, precisely so they can be trusted
-- — has no such roles, so the revokes and grants below would fail there with
-- "role does not exist" and nothing would be verified at all.
--
-- Creating them when absent is a no-op on a real project and never weakens the
-- revokes that follow.
-- ---------------------------------------------------------------------------
do $$
begin
  if not exists (select 1 from pg_roles where rolname = 'anon') then
    create role anon nologin noinherit;
  end if;
  if not exists (select 1 from pg_roles where rolname = 'authenticated') then
    create role authenticated nologin noinherit;
  end if;
  if not exists (select 1 from pg_roles where rolname = 'service_role') then
    create role service_role nologin noinherit bypassrls;
  end if;
end
$$;
--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- Foreign key to auth.users, added only where that table exists.
--
-- In Supabase a profile should disappear with the user it describes, so this
-- cascades. Drizzle cannot express the condition, and the condition is not
-- hypothetical: CI runs plain PostgreSQL, where `auth.users` does not exist and
-- an unconditional reference would fail to apply.
--
-- The profile is the only thing that cascades. Chain-derived rows are keyed by
-- wallet and contract address, not by user id, so deleting an account cannot
-- reach them — which is required, because chain history is immutable and a user
-- deleting their account must not be able to erase a payout they received.
-- ---------------------------------------------------------------------------
do $$
begin
  if exists (
    select 1 from information_schema.tables
    where table_schema = 'auth' and table_name = 'users'
  ) then
    alter table public.profiles
      add constraint profiles_user_id_fkey
      foreign key (user_id) references auth.users (id) on delete cascade;
  end if;
end
$$;
--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- updated_at, maintained by the database rather than by each writer.
--
-- Two different clients write this table: the browser (setting a display name)
-- and the API. Leaving each to remember the timestamp means one of them
-- eventually will not, and a stale `updated_at` is indistinguishable from a row
-- nobody has touched.
--
-- SECURITY INVOKER, the default, and deliberately so. It needs no privilege the
-- caller lacks — it only assigns to the row being written — so there is nothing
-- here that would justify SECURITY DEFINER. An invoker function that elevates
-- nothing is one fewer thing to reason about.
-- ---------------------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = pg_catalog, public
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;
--> statement-breakpoint

create trigger profiles_set_updated_at
  before update on public.profiles
  for each row
  execute function public.set_updated_at();
--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- Row Level Security: enabled, then the minimum that makes a profile usable.
-- ---------------------------------------------------------------------------
alter table public.profiles enable row level security;
--> statement-breakpoint

-- A user reads their own profile. `auth.uid()` is the verified session subject —
-- never a value supplied by the client, which is why the comparison is written
-- against the column rather than against a request parameter.
create policy profiles_select_own on public.profiles
  for select
  to authenticated
  using (auth.uid() = user_id);
--> statement-breakpoint

-- A user creates the row that describes them. `with check` is what stops a
-- client inserting a profile for somebody else; without it the policy would only
-- decide whether the statement runs, not what it may write.
--
-- Rows are created by the client rather than by a trigger on auth.users, because
-- such a trigger must be SECURITY DEFINER, and the document permits that only
-- where it is necessary and reviewed. A profile that does not exist yet is
-- simply unset, which is a state the schema already allows.
create policy profiles_insert_own on public.profiles
  for insert
  to authenticated
  with check (auth.uid() = user_id);
--> statement-breakpoint

-- A user edits their own profile. Both clauses are required: `using` decides
-- which rows may be touched, `with check` stops an update from reassigning the
-- row to another user and thereby deleting it from its owner's view.
create policy profiles_update_own on public.profiles
  for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);
--> statement-breakpoint

-- No DELETE policy is created, and no delete privilege is granted below.
-- Deleting an account is a documented server-side operation with consequences
-- for application data, and it must not be reachable by a single browser call
-- against a table whose row is the user's identity. Absent a policy, the delete
-- is denied.
--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- Grants: RLS is not a substitute for privileges.
--
-- Supabase grants the browser roles broad privileges on new tables in the
-- exposed schema by default, so the revoke is load-bearing rather than
-- ceremonial: without it, `anon` could reach a table whose every policy is
-- scoped to `authenticated` and still read it.
-- ---------------------------------------------------------------------------
revoke all on public.profiles from anon, authenticated;
--> statement-breakpoint

grant select, insert on public.profiles to authenticated;
--> statement-breakpoint

-- Update is granted per column, which is the whole point of granting it this
-- way. RLS cannot express "these fields but not those", so an update grant on
-- the table would let a client rewrite `user_id` — handing its profile to
-- another account, or orphaning it — and `created_at`, which is a historical
-- fact rather than a user-editable field. `updated_at` is maintained by the
-- trigger above and needs no grant.
grant update (display_name, avatar_path) on public.profiles to authenticated;
--> statement-breakpoint

-- The API and the indexer use the service role, which bypasses RLS. It is given
-- what those paths need and nothing more.
grant select, insert, update on public.profiles to service_role;
