-- Susu Protocol — wallet links, invites and notifications
--
-- These three tables are the application's own state. They are not derived from
-- the chain: nothing here can change a balance, decide a recipient, or authorise
-- a movement. What they hold is the convenience layer around a chain that
-- remains authoritative, and each one is secured according to what a client can
-- actually prove.
--
-- Generated by `drizzle-kit generate`, then extended by hand. Drizzle cannot
-- express RLS, policies, column-level grants, CHECK constraints or conditional
-- foreign keys, and all five are requirements here rather than embellishments.
-- Regenerating this file would drop them, so it is reviewed as source rather
-- than produced as output. The same is true of `0000_profiles.sql`.
--
-- THE ONE THEME IN THIS FILE
-- Two of these tables are deliberately *less* accessible than the UI would find
-- convenient, and both for the same reason: the browser is not a party that can
-- prove anything.
--
--   * A wallet binding is a claim to control a keypair. If a client could insert
--     it, the nonce-and-signature handshake would be theatre.
--   * An invite code is only worth something because it is unguessable. If a
--     client could list invite rows, it would not need to guess.
--
-- So `authenticated` gets to read its own wallet link, read and mark-read its own
-- notifications, and touch nothing else. `invite_links` is granted to no browser
-- role at all.

CREATE TABLE "invite_links" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"code" text NOT NULL,
	"group_contract_id" text NOT NULL,
	"created_by" uuid NOT NULL,
	"expires_at" timestamp with time zone,
	"max_uses" integer,
	"uses" integer DEFAULT 0 NOT NULL,
	"revoked_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "invite_links_code_unique" UNIQUE("code")
);
--> statement-breakpoint
CREATE TABLE "notifications" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"kind" text NOT NULL,
	"title" text NOT NULL,
	"body" text,
	"data" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"read_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "wallet_links" (
	"user_id" uuid PRIMARY KEY NOT NULL,
	"address" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "wallet_links_address_unique" UNIQUE("address")
);
--> statement-breakpoint
CREATE INDEX "invite_links_group_idx" ON "invite_links" USING btree ("group_contract_id");--> statement-breakpoint
CREATE INDEX "invite_links_created_by_idx" ON "invite_links" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX "notifications_user_created_idx" ON "notifications" USING btree ("user_id","created_at");--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- Supabase-managed roles, created only when absent.
--
-- `0000_profiles.sql` creates these too. Repeating the guard costs nothing and
-- means this migration does not depend on being applied second: the revokes and
-- grants below are the load-bearing part of this file, and a role that does not
-- exist would make them fail rather than make them unnecessary.
-- ---------------------------------------------------------------------------
do $$
begin
  if not exists (select 1 from pg_roles where rolname = 'anon') then
    create role anon nologin noinherit;
  end if;
  if not exists (select 1 from pg_roles where rolname = 'authenticated') then
    create role authenticated nologin noinherit;
  end if;
  if not exists (select 1 from pg_roles where rolname = 'service_role') then
    create role service_role nologin noinherit bypassrls;
  end if;
end
$$;
--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- Shape constraints.
--
-- Zod validates the same things at the edge, and that is not duplication for its
-- own sake: Zod protects the request path, these protect the table. The
-- difference matters for the code and address columns in particular, because
-- both are values the rest of the system treats as identities. A malformed
-- address that reached `wallet_links` would be a row that can never match an
-- on-chain member, and a malformed invite code would be a row that can never be
-- redeemed — neither would fail loudly at the point of writing.
-- ---------------------------------------------------------------------------

-- An invite code must be long and opaque. The floor is 22 base64url characters,
-- which is 132 bits; a future code path cannot quietly start issuing short,
-- structured, or address-derived codes without failing here first.
alter table public.invite_links
  add constraint invite_links_code_shape
  check (code ~ '^[A-Za-z0-9_-]{22,64}$');
--> statement-breakpoint

-- A code must not be *shaped like a Stellar address*, and this constraint exists
-- because the check above does not catch it. That is not a hypothetical: this
-- project's first invite implementation used the group's contract address as the
-- invite code, and a contract address is 56 characters of `[A-Z2-7]` — long,
-- high-entropy, and a perfect match for the pattern above.
--
-- The failure the shape check misses is not entropy, it is *discoverability*.
-- A contract address is published on the chain and readable by anyone, so a code
-- that merely looks random is still enumerable by walking addresses. Uniqueness
-- and length cannot express "not publicly derivable"; this can, for the one
-- shape that this project has already used by mistake.
alter table public.invite_links
  add constraint invite_links_code_not_an_address
  check (code !~ '^[GC][A-Z2-7]{55}$');
--> statement-breakpoint

-- A Soroban contract address: `C` followed by 55 base-32 characters. Catches a
-- group id pasted from the wrong field (a `G` account, or a transaction hash).
alter table public.invite_links
  add constraint invite_links_group_contract_shape
  check (group_contract_id ~ '^C[A-Z2-7]{55}$');
--> statement-breakpoint

-- Capacity, when set, is a positive ceiling. `max_uses = 0` is rejected rather
-- than treated as "unlimited", because a zero-use invite is far more likely to
-- be a bug than an intention, and the null case already means unlimited.
alter table public.invite_links
  add constraint invite_links_max_uses_positive
  check (max_uses is null or max_uses > 0);
--> statement-breakpoint

-- The invariant that makes `uses` trustworthy: it never exceeds the ceiling and
-- never goes negative. Joins increment it under a row lock, so a violation here
-- would mean the lock failed — which is exactly the bug worth hearing about.
alter table public.invite_links
  add constraint invite_links_uses_within_capacity
  check (uses >= 0 and (max_uses is null or uses <= max_uses));
--> statement-breakpoint

-- `G` is a classic account and `C` a contract, and both are legitimate members:
-- a wallet-contract member is a `C` address. A `G`-only constraint would reject
-- real wallets.
alter table public.wallet_links
  add constraint wallet_links_address_shape
  check (address ~ '^[GC][A-Z2-7]{55}$');
--> statement-breakpoint

-- Kinds are lowercase snake case. Deliberately not a Postgres enum: the set of
-- kinds grows with the product (invites, due and confirmed contributions, payout
-- ready and confirmed, completion, security events), and an enum would make each
-- addition a migration on a table the indexer also writes to. The format check
-- still stops a typo becoming a kind nobody reads.
alter table public.notifications
  add constraint notifications_kind_shape
  check (kind ~ '^[a-z][a-z0-9_]{0,39}$');
--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- Foreign keys to auth.users, added only where that table exists.
--
-- All three cascade: these tables describe a user's own application data, and
-- the document requires account deletion to have documented handling of it.
-- Deleting the account removes the wallet binding, the invites the user issued
-- and their notifications.
--
-- Note what is *not* here. Chain-derived rows are keyed by wallet and contract
-- address, never by user id, so nothing in this cascade can reach a
-- contribution, a payout or a group member. Chain history is immutable, and a
-- user deleting their account must not be able to erase a payout they received.
-- That separation is enforced by the key choice, not by remembering.
--
-- The condition is not hypothetical: CI runs plain PostgreSQL, where `auth` does
-- not exist and an unconditional reference would fail to apply.
-- ---------------------------------------------------------------------------
do $$
begin
  if exists (
    select 1 from information_schema.tables
    where table_schema = 'auth' and table_name = 'users'
  ) then
    alter table public.wallet_links
      add constraint wallet_links_user_id_fkey
      foreign key (user_id) references auth.users (id) on delete cascade;

    alter table public.notifications
      add constraint notifications_user_id_fkey
      foreign key (user_id) references auth.users (id) on delete cascade;

    alter table public.invite_links
      add constraint invite_links_created_by_fkey
      foreign key (created_by) references auth.users (id) on delete cascade;
  end if;
end
$$;
--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- updated_at, maintained by the database rather than by each writer.
--
-- Reuses `public.set_updated_at()` from `0000_profiles.sql`, which is SECURITY
-- INVOKER and sets its search_path. Only wallet_links needs it: an invite has no
-- editable field (it is revoked, not edited) and a notification's only mutation
-- is `read_at`, which is a fact about the user rather than a revision of the row.
-- ---------------------------------------------------------------------------
create trigger wallet_links_set_updated_at
  before update on public.wallet_links
  for each row
  execute function public.set_updated_at();
--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- Row Level Security: enabled on all three, before any grant.
-- ---------------------------------------------------------------------------
alter table public.wallet_links enable row level security;
--> statement-breakpoint
alter table public.invite_links enable row level security;
--> statement-breakpoint
alter table public.notifications enable row level security;
--> statement-breakpoint

-- A user sees the wallet they have proven they control. There is no insert
-- policy and no update policy, and that is the security property rather than an
-- omission: the binding is established by the API after it has verified a
-- signature over a server-issued nonce. If a client could insert or update here,
-- it could claim any address, and the signature check would be decorative.
create policy wallet_links_select_own on public.wallet_links
  for select
  to authenticated
  using (auth.uid() = user_id);
--> statement-breakpoint

-- No policies are created on invite_links at all, so every operation is denied
-- for `anon` and `authenticated`. This is intentional and is the point of the
-- table: a client that can list invite rows has defeated the unguessability of
-- the code without guessing one. Codes are created and redeemed server-side.
--
-- A note for whoever is tempted to add "the creator may read their own invites":
-- that policy would let a creator enumerate, and it buys nothing, because the
-- creator already knows the code they just created — it is returned once, in the
-- response to the creation request.
--> statement-breakpoint

-- A user reads their own notifications.
create policy notifications_select_own on public.notifications
  for select
  to authenticated
  using (auth.uid() = user_id);
--> statement-breakpoint

-- A user marks their own notification read. Both clauses are required: `using`
-- decides which rows may be touched, `with check` stops an update from
-- reassigning the row to another user. The column grant below is what restricts
-- this to `read_at` — RLS alone cannot say "this column but not that one".
create policy notifications_update_own on public.notifications
  for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);
--> statement-breakpoint

-- No insert policy and no delete policy on notifications. A client that could
-- write here could fabricate a message saying a payout had been confirmed, and a
-- notification a user cannot trust is worse than no notification. Trusted paths
-- write with the service role.

-- ---------------------------------------------------------------------------
-- Grants: RLS is not a substitute for privileges.
--
-- Supabase grants the browser roles broad privileges on new tables in the
-- exposed schema by default, so each revoke below is load-bearing. Without them,
-- `invite_links` in particular would be readable by `anon` — the table has no
-- policies, but RLS only applies to roles it is enforced against, and a table
-- with no policy denies everything only once the privilege question is settled
-- in the right order.
-- ---------------------------------------------------------------------------
revoke all on public.wallet_links from anon, authenticated;
--> statement-breakpoint
grant select on public.wallet_links to authenticated;
--> statement-breakpoint

-- Nothing for `authenticated`, and nothing for `anon`. See the policy note above.
revoke all on public.invite_links from anon, authenticated;
--> statement-breakpoint

revoke all on public.notifications from anon, authenticated;
--> statement-breakpoint
grant select on public.notifications to authenticated;
--> statement-breakpoint

-- Granted per column, which is the whole point. An update grant on the table
-- would let a client rewrite `title`, `body` or `user_id` — inventing a message,
-- or handing their notification to another account. `read_at` is the only field
-- a user has any business changing.
grant update (read_at) on public.notifications to authenticated;
--> statement-breakpoint

-- The API uses the service role, which bypasses RLS. It writes what the browser
-- may only read.
grant select, insert, update, delete on public.wallet_links to service_role;
--> statement-breakpoint
grant select, insert, update on public.invite_links to service_role;
--> statement-breakpoint
grant select, insert, update, delete on public.notifications to service_role;
