-- Susu Protocol — single-use nonce records and invite redemptions
--
-- Generated by `drizzle-kit generate`, then extended by hand. Drizzle cannot
-- express RLS, policies, column-level grants, CHECK constraints or conditional
-- foreign keys, and all of them are requirements here. Regenerating this file
-- would drop them, so it is reviewed as source rather than produced as output.
-- The same is true of `0000_profiles.sql` and `0001_invites_and_linking.sql`.
--
-- THE ONE THEME IN THIS FILE
-- Both tables hold a fact that *cannot be derived from the request*, which is
-- why they are tables rather than more columns on what already exists:
--
--   * `wallet_link_nonces` — the nonce is an HMAC-signed token, so the server can
--     validate one without a lookup and rotating the secret invalidates every
--     outstanding nonce at once. What a signature cannot express is *spent*. A
--     signed token verifies as many times as it is presented until it expires, so
--     single use has to be remembered, and this is where.
--   * `invite_redemptions` — `invite_links.uses` is a counter, and a counter
--     cannot say *who* has already redeemed a code. Without that, a member who
--     opens their invite link twice consumes two uses, and a limited code is
--     exhausted on a group that is not full. Idempotence needs the identity of
--     the redeemer, not just a total.
--
-- Both are server-only. Neither is granted to a browser role at all, and RLS is
-- enabled with no policies, so every operation from `anon` or `authenticated` is
-- denied by default: a client that could insert a redemption could burn a
-- limited invite's uses without joining, and a client that could insert a spent
-- nonce could mount a partial denial of its own link flow.

CREATE TABLE "invite_redemptions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"invite_id" uuid NOT NULL,
	"user_id" uuid NOT NULL,
	"redeemed_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "wallet_link_nonces" (
	"jti" text PRIMARY KEY NOT NULL,
	"user_id" uuid NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"consumed_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX "invite_redemptions_invite_user_key" ON "invite_redemptions" USING btree ("invite_id","user_id");--> statement-breakpoint
CREATE INDEX "invite_redemptions_user_idx" ON "invite_redemptions" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "wallet_link_nonces_expires_at_idx" ON "wallet_link_nonces" USING btree ("expires_at");--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- Supabase-managed roles, created only when absent.
--
-- Repeated from the earlier migrations so this file does not depend on being
-- applied in order: the revokes and grants below are load-bearing, and a role
-- that does not exist would make them fail rather than make them unnecessary.
-- ---------------------------------------------------------------------------
do $$
begin
  if not exists (select 1 from pg_roles where rolname = 'anon') then
    create role anon nologin noinherit;
  end if;
  if not exists (select 1 from pg_roles where rolname = 'authenticated') then
    create role authenticated nologin noinherit;
  end if;
  if not exists (select 1 from pg_roles where rolname = 'service_role') then
    create role service_role nologin noinherit bypassrls;
  end if;
end
$$;
--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- Shape constraints.
--
-- The nonce id is the value the client presents back, and it is generated by
-- this service as 32 random bytes in base64url. Pinning the alphabet and a floor
-- on the length means a future code path cannot start issuing short, structured
-- or guessable ids without failing here first — and a guessable id would matter,
-- because the id is what makes replay detection specific to one nonce.
-- ---------------------------------------------------------------------------
alter table public.wallet_link_nonces
  add constraint wallet_link_nonces_jti_shape
  check (jti ~ '^[A-Za-z0-9_-]{16,128}$');
--> statement-breakpoint

-- A redemption has to point at a real invite. Unlike the invite's own group
-- reference — which deliberately has no foreign key, because a group row belongs
-- to the indexer and may not have arrived yet — this reference is between two
-- tables this service owns, so it can and should be enforced.
--
-- Cascading on delete keeps the counter and the record of who redeemed it from
-- outliving the invite they describe.
alter table public.invite_redemptions
  add constraint invite_redemptions_invite_id_fkey
  foreign key (invite_id) references public.invite_links (id) on delete cascade;
--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- Foreign keys to auth.users, added only where that table exists.
--
-- Both cascade. A spent nonce and a redemption are parts of an account's
-- application data, and the document requires account deletion to have
-- documented handling of it.
--
-- Note, again, what is *not* reachable: nothing here is keyed by wallet or
-- contract address, so deleting an account cannot touch chain history.
--
-- The condition is not hypothetical: CI runs plain PostgreSQL, where `auth` does
-- not exist and an unconditional reference would fail to apply.
-- ---------------------------------------------------------------------------
do $$
begin
  if exists (
    select 1 from information_schema.tables
    where table_schema = 'auth' and table_name = 'users'
  ) then
    alter table public.wallet_link_nonces
      add constraint wallet_link_nonces_user_id_fkey
      foreign key (user_id) references auth.users (id) on delete cascade;

    alter table public.invite_redemptions
      add constraint invite_redemptions_user_id_fkey
      foreign key (user_id) references auth.users (id) on delete cascade;
  end if;
end
$$;
--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- Row Level Security: enabled on both, before any grant.
--
-- No policies are created, for either table, and that is the security posture
-- rather than an omission. With RLS enabled and no policy, every operation is
-- denied for every role it is enforced against; the API reaches these tables with
-- the service role, which bypasses RLS by design.
--
-- This is the same reasoning as `invite_links` in the previous migration: a
-- client has no legitimate use for either table. It never needs to read a nonce
-- (it is given one, once, in a response) and never needs to read a redemption
-- (the answer it wants is the group, which the join endpoint returns).
-- ---------------------------------------------------------------------------
alter table public.wallet_link_nonces enable row level security;
--> statement-breakpoint
alter table public.invite_redemptions enable row level security;
--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- Grants: RLS is not a substitute for privileges.
--
-- Supabase grants browser roles broad privileges on new tables in the exposed
-- schema by default, so the revokes are load-bearing rather than tidy. A table
-- with no policies denies everything only once the privilege question is
-- settled in the right order.
-- ---------------------------------------------------------------------------
revoke all on public.wallet_link_nonces from anon, authenticated;
--> statement-breakpoint
revoke all on public.invite_redemptions from anon, authenticated;
--> statement-breakpoint

-- The API uses the service role, which bypasses RLS. It writes what the browser
-- is granted nothing on.
grant select, insert, update, delete on public.wallet_link_nonces to service_role;
--> statement-breakpoint
grant select, insert, update, delete on public.invite_redemptions to service_role;
