-- Susu Protocol — group registrations
--
-- Generated by `drizzle-kit generate`, then extended by hand. Drizzle cannot
-- express RLS, policies, grants or CHECK constraints, and all of them are
-- requirements here. Regenerating this file would drop them, so it is reviewed as
-- source rather than produced as output. The same is true of the three earlier
-- migrations.
--
-- THE PROBLEM
-- A group's address is the hash of its own deployment, so the only way to learn
-- that a group exists is to watch the Factory emit it. The indexer does that on a
-- five-minute schedule, so between a creator's confirmation and the next indexing
-- run the address is real, public, and unknown to this API.
--
-- `invite_links` was already built for that window: it deliberately holds the
-- group address as plain text with no foreign key, because "an invite may
-- legitimately be created during the window before the indexer has seen the
-- group's creation event". The invite route then refused to use that freedom —
-- it asked the index whether the group existed, and answered `group_not_found`
-- for up to five minutes after creation. The document's core journey is "Create
-- group. Set members and payout order. Share invite.", and this table is what lets
-- the middle of it work.
--
-- WHAT IS STORED, AND WHAT IS NOT
-- An address, the account that claimed it, and an expiry. No amount, no
-- membership, no status, no transaction hash. A row here does not make a contract
-- exist and nothing financial reads it. `groups` stays the indexer's table and the
-- index stays the authority; this is a claim that stops being believed on its own,
-- by clock, without anything needing to run.

CREATE TABLE "group_registrations" (
	"contract_id" text PRIMARY KEY NOT NULL,
	"registered_by" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"expires_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE INDEX "group_registrations_expires_at_idx" ON "group_registrations" USING btree ("expires_at");--> statement-breakpoint
CREATE INDEX "group_registrations_registered_by_idx" ON "group_registrations" USING btree ("registered_by");--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- Supabase-managed roles, created only when absent.
--
-- Repeated from the earlier migrations so this file does not depend on being
-- applied in order: the revokes and grants below are load-bearing, and a role that
-- does not exist would make them fail rather than make them unnecessary.
-- ---------------------------------------------------------------------------
do $$
begin
  if not exists (select 1 from pg_roles where rolname = 'anon') then
    create role anon nologin noinherit;
  end if;
  if not exists (select 1 from pg_roles where rolname = 'authenticated') then
    create role authenticated nologin noinherit;
  end if;
  if not exists (select 1 from pg_roles where rolname = 'service_role') then
    create role service_role nologin noinherit bypassrls;
  end if;
end
$$;
--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- Shape constraints.
--
-- The address must be a Soroban contract id. This is the same pattern the group
-- routes validate against, repeated here because the database is the last place a
-- malformed value can be refused, and a registration is the one group-ish row this
-- service writes itself rather than copying from the ledger.
--
-- The window must be positive. A zero or negative interval would insert a row that
-- is already expired, which reads as a successful registration and behaves as
-- none — the kind of silent no-op worth failing on.
-- ---------------------------------------------------------------------------
alter table public.group_registrations
  add constraint group_registrations_contract_id_shape
  check (contract_id ~ '^C[A-Z2-7]{55}$');
--> statement-breakpoint
alter table public.group_registrations
  add constraint group_registrations_window_positive
  check (expires_at > created_at);
--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- Foreign key to auth.users, added only where that table exists.
--
-- Cascades. This mirrors the conditional reference in the previous migration: CI
-- runs plain PostgreSQL, where `auth` does not exist and an unconditional
-- reference would fail to apply.
-- ---------------------------------------------------------------------------
do $$
begin
  if exists (
    select 1 from information_schema.tables
    where table_schema = 'auth' and table_name = 'users'
  ) then
    alter table public.group_registrations
      add constraint group_registrations_registered_by_fkey
      foreign key (registered_by) references auth.users (id) on delete cascade;
  end if;
end
$$;
--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- Row Level Security: enabled before any grant, with no policies.
--
-- That is the posture, not an omission. With RLS enabled and no policy, every
-- operation is denied for every role it is enforced against, and the API reaches
-- this table with the service role, which bypasses RLS by design.
--
-- A client has no legitimate use for this table. It learns the outcome of its own
-- registration from the response to the request that made it, and every question
-- it might otherwise ask — is this a group, what is its state — is answered by
-- reading the contract, which is the authority anyway. Handing a browser read
-- access would mean publishing a list of addresses that are believed to be groups
-- but are not yet verified by the index, which is a list of exactly the addresses
-- an attacker would want to present as real.
-- ---------------------------------------------------------------------------
alter table public.group_registrations enable row level security;
--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- Grants: RLS is not a substitute for privileges.
--
-- Supabase grants browser roles broad privileges on new tables in the exposed
-- schema by default, so the revokes are load-bearing rather than tidy. A table
-- with no policies denies everything only once the privilege question is settled
-- in the right order.
-- ---------------------------------------------------------------------------
revoke all on public.group_registrations from anon, authenticated;
--> statement-breakpoint

grant select, insert, update, delete on public.group_registrations to service_role;
